In [3]:
import numpy as np

In [4]:
x = np.array([1,2,3,4])

In [5]:
print(x)

[1 2 3 4]


In [6]:
print(type(x))

<class 'numpy.ndarray'>


In [7]:
print(x.shape)

(4,)


In [9]:
y = np.array([[1,2],[3,4]])

In [10]:
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [11]:
z = np.array([[1+0.j,2+5.j]])

In [12]:
print(z)
print(z.shape)

[[1.+0.j 2.+5.j]]
(1, 2)


In [13]:
a = np.zeros((2,3))

In [14]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(a.shape)

(2, 3)


In [16]:
b = np.ones((2,3),dtype=int)

In [17]:
print(b)

[[1 1 1]
 [1 1 1]]


In [18]:
d = np.eye(3)

In [19]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
e = np.arange(12, 21)

In [23]:
print(e)

[12 13 14 15 16 17 18 19 20]


In [24]:
e = np.arange(5,20,3)

In [25]:
print(e)

[ 5  8 11 14 17]


In [26]:
f = np.linspace(1,20,7)

In [27]:
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [28]:
g = np.random.random((3,4))

In [29]:
print(g)

[[0.34537145 0.37623118 0.50187914 0.1858881 ]
 [0.31296438 0.68192396 0.51061051 0.01042125]
 [0.24588899 0.99199363 0.48971279 0.70682007]]


In [30]:
h = np.random.random((3,4))

In [31]:
print(h.reshape(2,2,3))

[[[0.8895344  0.44620512 0.13818442]
  [0.35044682 0.81816129 0.44618855]]

 [[0.60506478 0.310828   0.97995711]
  [0.99176159 0.03425248 0.27740614]]]


In [33]:
x = np.arange(12)
print(x)
print(x[4])


[ 0  1  2  3  4  5  6  7  8  9 10 11]
4


In [34]:
print(x[-1])

11


In [35]:
x.resize(3,4)

In [36]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
print(x[-1,-1])

11


In [38]:
y = np.arange(1,26)
print(y)
print(y[:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[1 2 3]


In [39]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [40]:
print(y[10:15])

[11 12 13 14 15]


In [41]:
print(y[-5:])

[21 22 23 24 25]


In [44]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [45]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [46]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [47]:
y = y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [48]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [49]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [50]:
print(y[:,-1])

[ 5 10 15 20 25]


In [51]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [52]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [53]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [54]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [55]:
print(a>3)

[False False False  True  True]


In [56]:
a = np.arange(0,4).reshape((2,2))

In [57]:
b = np.eye(2)

In [58]:
print(a*b)

[[0. 0.]
 [0. 3.]]


In [59]:
print(np.dot(a,b))

[[0. 1.]
 [2. 3.]]


In [60]:
x = np.arange(1,10).reshape(3,3)

In [61]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
print(x.sum(axis=1))

[ 6 15 24]


In [63]:
x = np.arange( 1,19).reshape(3,3,2)

In [64]:
print(x.sum(axis=1))

[[ 9 12]
 [27 30]
 [45 48]]


In [65]:
x = np.arange(1,10).reshape(3,3)

In [66]:
print(x)
print(x.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [67]:
print(x.max(axis=0))

[7 8 9]


In [68]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
